version: '3.8'
services:
  blood-bank-db:
    image: postgres:13
    environment:
      POSTGRES_DB: blood_bank_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
    - 5433:5432
    volumes:
    - blood_bank_data:/var/lib/postgresql/data
  blood-bank-service:
    build: .
    ports:
    - 8001:8001
    environment:
      DATABASE_URL: postgresql://user:password@blood-bank-db:5432/blood_bank_db
    depends_on:
    - blood-bank-db
    volumes:
    - .:/app
volumes:
  blood_bank_data: null
