version: '3.8'
services:
  cybersecurity-db:
    image: postgres:15
    environment:
      POSTGRES_DB: cybersecurity_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
    - 5438:5432
    volumes:
    - cybersecurity_data:/var/lib/postgresql/data
  cybersecurity-service:
    build: .
    ports:
    - 8008:8008
    environment:
      DATABASE_URL: postgresql://user:password@cybersecurity-db:5432/cybersecurity_db
    depends_on:
    - cybersecurity-db
    volumes:
    - .:/app
volumes:
  cybersecurity_data: null
