version: '3.8'
services:
  insurance-db:
    image: postgres:13
    environment:
      POSTGRES_DB: insurance_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
    - 5434:5432
    volumes:
    - insurance_data:/var/lib/postgresql/data
  insurance-service:
    build: .
    ports:
    - 8004:8004
    environment:
      DATABASE_URL: postgresql://user:password@insurance-db:5432/insurance_db
    depends_on:
    - insurance-db
    volumes:
    - .:/app
volumes:
  insurance_data: null
